### ISSUE TITLE
elmo embedding

### ISSUE THREAD

**Issue by jingjojo** [noc-lab/clinical_concept_extraction#2]
Hello,

I want to use the pre-trained embeddings you made available. Could you please let me know if it is the model.data-00000-of-00001 file that I have to load in tensorflow to get the embeddings? Thanks.

**Comment by henghuiz-zz** [comment]
Hi,

Please check the release page for elmo.tar.gz. Unzip the file and you will find options.json and mimic_wiki.hdf5. Those file is compatible for the elmo repo of AllenNLP. Alternatively, you can see function `ELMO_MIMIC` in `clinical_concept_extraction/elmo_vector.py` for using this embedding.

**Comment by jingjojo** [comment]
Thanks a lot for the reply! Is it possible to run elmo_vector.py with cpu(not gpu)?

**Comment by henghuiz-zz** [comment]
The code runs on both CPU and GPU. But, of course, running on CPU is slower than running on GPU.

**Comment by jingjojo** [comment]
Thanks again!
